name: gen
description: "A new Flutter package project."
version: 0.0.1
homepage: none

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.8.0
  flutter_svg: ^2.2.0
  lottie: ^3.3.1
  envied: ^1.1.1
  equatable: ^2.0.7
  flutter_gen: ^5.10.0
  vexana: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  very_good_analysis: ^9.0.0
  build_runner: ^2.5.4
  envied_generator: ^1.1.1
  json_serializable: ^6.6.1
  flutter_gen_runner: ^5.10.0


flutter_gen:
  output: lib/src/asset/
  integrations:
    lottie: true
    flutter_svg: true
  colors:
    inputs:
      - assets/color/colors.xml

flutter:
  assets:
    - assets/color/
    - assets/lottie/
    - assets/icons/
    - assets/images/
