targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator:
         generate_for:
           - lib/**/**_view.dart
      auto_route_generator:auto_route_generator:
         generate_for:
            - lib/product/navigation/app_router.dart